/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frontend;

import javax.swing.JOptionPane;
import backend.*;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;

public class FrmPenjualan extends javax.swing.JFrame {
    /**
     * Creates new form FrmPenjualan
     */
    Date date = new Date();
    SimpleDateFormat formatter = new SimpleDateFormat("yyyy/MM/dd");
    SimpleDateFormat waktu = new SimpleDateFormat("yyMMddHHmmss");
            
    public FrmPenjualan() {
        initComponents();
        inisialisasi();
        tampilCmbKategori();
        Toolkit tk = getToolkit();
        Dimension size = tk.getScreenSize();
        setLocation(size.width/2-getWidth()/2, size.width/5-getHeight()/5);
        
        //Color c = new Color(255, 255, 255);
        this.getContentPane().setBackground(new Color(51, 51, 44));
    }
    
    public void inisialisasi(){
        Date dt = new Date();    
        System.out.println("tes");
        labelId.setText("TVN"+waktu.format(dt));
        tampilkanData();
        tampilkanPesanan();
        labelTotal.setText("0");
        labelQty.setText("0");
        Penjualan penjualan = new Penjualan();
        penjualan.setId(labelId.getText());
        penjualan.setTglPenjualan(formatter.format(date));
        penjualan.setTotalHarga(Integer.parseInt(labelTotal.getText()));
        penjualan.setTotalQty(Integer.parseInt(labelQty.getText()));
        penjualan.save();
        
    }
    public void tampilkanPesanan(){
        String[] kolom = {"ID","Menu", "QTY", "Harga"};
        ArrayList<DetailPenjualan> list = new DetailPenjualan().getAllby(labelId.getText());
        Object rowData[] = new Object[4];

        tblPenjualan.setModel(new DefaultTableModel(new Object[][]{}, kolom));

        for (DetailPenjualan detail : list) {
            rowData[0] = detail.getIds();
            rowData[1] = detail.getMenu().getNama();
            rowData[2] = detail.getQty();
            rowData[3] = detail.getHarga();

            ((DefaultTableModel) tblPenjualan.getModel()).addRow(rowData);
        }
    }
    
    public void tampilkanData() {
        String[] kolom = {"ID", "Nama Menu", "Jenis", "Harga"};
        ArrayList<Menu> list = new Menu().getAll();
        Object rowData[] = new Object[5];

        tblMenu.setModel(new DefaultTableModel(new Object[][]{}, kolom));

        for (Menu menu : list) {
            rowData[0] = menu.getId();
            rowData[1] = menu.getNama();
            rowData[2] = menu.getKategori().getNama();
            rowData[3] = (menu.getRcost()+menu.getScost());

            ((DefaultTableModel) tblMenu.getModel()).addRow(rowData);
        }
    }
    
    public void tampilCmbKategori() {
        cmbKategori.setModel(new DefaultComboBoxModel(new Kategori().getAll().toArray()));
    }
    
    public void cari(String keyword) {
        String[] kolom = {"ID", "Nama Menu", "Jenis", "Harga"};
        ArrayList<Menu> list = new Menu().search(keyword);
        Object rowData[] = new Object[5];

        tblMenu.setModel(new DefaultTableModel(new Object[][]{}, kolom));

        for (Menu menu : list) {
            rowData[0] = menu.getId();
            rowData[1] = menu.getNama();
            rowData[2] = menu.getKategori().getNama();
            rowData[3] = (menu.getRcost()+menu.getScost());

            ((DefaultTableModel) tblMenu.getModel()).addRow(rowData);
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        labelId = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        labelTotal = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMenu = new javax.swing.JTable();
        btnHapus = new javax.swing.JButton();
        btnBayar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPenjualan = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        labelQty = new javax.swing.JLabel();
        Menu = new javax.swing.JButton();
        KategoriBtn = new javax.swing.JButton();
        BtnDisabled = new javax.swing.JButton();
        cmbKategori = new javax.swing.JComboBox<>();
        txtCari = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Form Penjualan");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("No Nota");

        labelId.setForeground(new java.awt.Color(255, 255, 255));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Total");

        labelTotal.setForeground(new java.awt.Color(255, 255, 255));
        labelTotal.setText("0");

        tblMenu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMenuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblMenu);

        btnHapus.setBackground(new java.awt.Color(15, 29, 91));
        btnHapus.setForeground(new java.awt.Color(255, 255, 255));
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnBayar.setBackground(new java.awt.Color(15, 29, 91));
        btnBayar.setForeground(new java.awt.Color(255, 255, 255));
        btnBayar.setText("Bayar");
        btnBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBayarActionPerformed(evt);
            }
        });

        tblPenjualan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblPenjualan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPenjualanMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblPenjualan);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Qty");

        labelQty.setForeground(new java.awt.Color(255, 255, 255));
        labelQty.setText("0");

        Menu.setBackground(new java.awt.Color(15, 29, 91));
        Menu.setForeground(new java.awt.Color(255, 255, 255));
        Menu.setText("Form Menu");
        Menu.setPreferredSize(new java.awt.Dimension(110, 40));
        Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuActionPerformed(evt);
            }
        });

        KategoriBtn.setBackground(new java.awt.Color(15, 29, 91));
        KategoriBtn.setForeground(new java.awt.Color(255, 255, 255));
        KategoriBtn.setText("Form Kategori");
        KategoriBtn.setPreferredSize(new java.awt.Dimension(110, 40));
        KategoriBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KategoriBtnActionPerformed(evt);
            }
        });

        BtnDisabled.setBackground(new java.awt.Color(51, 51, 44));
        BtnDisabled.setForeground(new java.awt.Color(255, 255, 255));
        BtnDisabled.setText("Form Penjualan");
        BtnDisabled.setEnabled(false);
        BtnDisabled.setPreferredSize(new java.awt.Dimension(110, 40));
        BtnDisabled.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDisabledActionPerformed(evt);
            }
        });

        cmbKategori.setForeground(new java.awt.Color(255, 255, 255));
        cmbKategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbKategoriActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(15, 29, 91));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Cari");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(KategoriBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnDisabled, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelTotal)
                                    .addComponent(labelId, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelQty)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(btnHapus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBayar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1)
                                .addGap(29, 29, 29)
                                .addComponent(cmbKategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnDisabled, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(KategoriBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(labelId, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(labelTotal))))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(labelQty))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbKategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMenuMouseClicked
        DefaultTableModel model = (DefaultTableModel)tblMenu.getModel();
        int row = tblMenu.getSelectedRow();
        
        Menu menu = new Menu();        
        DetailPenjualan detail = new DetailPenjualan();
        menu = menu.getById(Integer.parseInt(model.getValueAt(row, 0).toString()));
        int qty = Integer.parseInt(JOptionPane.showInputDialog(this, "Masukkan Jumlah"));
        
        detail.setId((labelId.getText()));
        detail.setTgl_penjualan(formatter.format(date));
        detail.setMenu(menu);
        detail.setQty(qty);
        detail.setHarga(qty*(menu.getRcost()+menu.getScost()));
        detail.save();
        
        labelTotal.setText(String.valueOf(Integer.parseInt(labelTotal.getText())+detail.getHarga()));
        labelQty.setText(String.valueOf(Integer.parseInt(labelQty.getText())+detail.getQty()));
        tampilkanPesanan();
    }//GEN-LAST:event_tblMenuMouseClicked

    private void tblPenjualanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPenjualanMouseClicked
        DefaultTableModel model = (DefaultTableModel)tblPenjualan.getModel();
        int row = tblPenjualan.getSelectedRow();
        DetailPenjualan detail = new DetailPenjualan();
        detail = detail.getById((model.getValueAt(row, 0).toString()));
    }//GEN-LAST:event_tblPenjualanMouseClicked

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        DefaultTableModel model = (DefaultTableModel)tblPenjualan.getModel();
        int row = tblPenjualan.getSelectedRow();

        DetailPenjualan detail = new DetailPenjualan().getById(model.getValueAt(row, 0).toString());
        labelTotal.setText(String.valueOf(Integer.parseInt(labelTotal.getText())-detail.getHarga()));
        labelQty.setText(String.valueOf(Integer.parseInt(labelQty.getText())-detail.getQty()));
        detail.delete();
        tampilkanPesanan();
    }//GEN-LAST:event_btnHapusActionPerformed

    private void MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuActionPerformed
        FrmMenu menu = new FrmMenu();
        menu.setVisible(true);
        dispose();
    }//GEN-LAST:event_MenuActionPerformed

    private void KategoriBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KategoriBtnActionPerformed
        FrmKategori kategori = new FrmKategori();
        kategori.setVisible(true);
        dispose();
    }//GEN-LAST:event_KategoriBtnActionPerformed

    private void BtnDisabledActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDisabledActionPerformed
        
    }//GEN-LAST:event_BtnDisabledActionPerformed

    private void btnBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBayarActionPerformed
                  
        Penjualan penjualan = new Penjualan();
        penjualan.setId(labelId.getText());
        penjualan.setTglPenjualan(formatter.format(date));
        penjualan.setTotalHarga(Integer.parseInt(labelTotal.getText()));
        penjualan.setTotalQty(Integer.parseInt(labelQty.getText()));
        penjualan.save();
        JOptionPane.showMessageDialog(this,"Total Pembelian"+penjualan.getTotalHarga());
        inisialisasi();
    }//GEN-LAST:event_btnBayarActionPerformed

    private void cmbKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbKategoriActionPerformed
        Object selected = cmbKategori.getSelectedItem();
        cari(String.valueOf(selected));
    }//GEN-LAST:event_cmbKategoriActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        cari(txtCari.getText());
    }//GEN-LAST:event_jButton1ActionPerformed

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPenjualan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnDisabled;
    private javax.swing.JButton KategoriBtn;
    private javax.swing.JButton Menu;
    private javax.swing.JButton btnBayar;
    private javax.swing.JButton btnHapus;
    private javax.swing.JComboBox<String> cmbKategori;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel labelId;
    private javax.swing.JLabel labelQty;
    private javax.swing.JLabel labelTotal;
    private javax.swing.JTable tblMenu;
    private javax.swing.JTable tblPenjualan;
    private javax.swing.JTextField txtCari;
    // End of variables declaration//GEN-END:variables
}
